Repository KU-MoneyMate/MoneyMate_Android, pull requests merged in 2025-08, with the labels that each got.

#23 [FEAT] 회원가입 id/pw 검증, sms 인증 구현
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/request/LogoutRequest.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/request/PhoneVerificationRequest.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/CheckExistingIdResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/LogoutResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/PhoneVerificationCodeResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/PhoneVerificationResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/repository/AuthRepository.kt
  app/src/main/java/com/moneymate/moneymate/data/service/AuthService.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/AuthViewModel.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpIDScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpPWScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpPhoneScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpVerificationScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/common/BottomFullWidthButton.kt
  app/src/main/java/com/moneymate/moneymate/util/auth/AuthInputValidation.kt
Labels: feat

#24 [Refactor] 각 화면에서의 기본 좌우 padding 값 수정
  app/src/main/java/com/moneymate/moneymate/ui/asset/screen/AddAccountScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/asset/screen/AddAssetScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/asset/screen/HomeScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/asset/screen/TransactionHistoryScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/LoginScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpIDScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpNameScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpPWScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpPhoneScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpVerificationScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/common/MoneyMateMenuButton.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/screen/FinanceScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/screen/ManageScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/screen/RetireInputScreen.kt
Labels: refactor

#28 [UI, FEAT] 소비통계 조회 화면 UI, 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/moneymate/moneymate/data/dto/manage/response/SpendingStatsResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/repository/ManageRepository.kt
  app/src/main/java/com/moneymate/moneymate/data/service/ManageService.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/ManageViewModel.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/component/SpendingStatisticsChart.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/component/SpendingStatisticsItem.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/screen/SpendingStatisticsScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/navigation/MoneyMateNavGraph.kt
  app/src/main/java/com/moneymate/moneymate/util/DateUtil.kt
  settings.gradle.kts
Labels: feat, ui
