Repository KU-MoneyMate/MoneyMate_Android, pull requests merged in 2025-07, with the labels that each got.

#18 [REFACTOR, FEAT] 회원가입 초기 기능 구현
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/request/IdPhoneCheckRequest.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/request/LoginRequest.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/request/PhoneVerificationCodeRequest.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/request/RegisterRequest.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/IdPhoneCheckResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/LoginResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/auth/response/PhoneVerificationCodeResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/repository/AuthRepository.kt
  app/src/main/java/com/moneymate/moneymate/data/service/AuthService.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/AuthViewModel.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/LoginScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpIDScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpNameScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpPWScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpPhoneScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/auth/screen/SignUpVerificationScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/navigation/AuthNavGraph.kt
  app/src/main/java/com/moneymate/moneymate/ui/navigation/MoneyMateNavGraph.kt
Labels: feat, refactor

#20 [feat] 경제 뉴스 화면 구성 및 api 연결
  app/src/main/java/com/moneymate/moneymate/data/dto/finance/NewsInfo.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/finance/response/NewsDetailResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/dto/finance/response/NewsListResponse.kt
  app/src/main/java/com/moneymate/moneymate/data/repository/FinanceRepository.kt
  app/src/main/java/com/moneymate/moneymate/data/service/FinanceService.kt
  app/src/main/java/com/moneymate/moneymate/ui/common/MoneyMateMenuButton.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/FinanceViewModel.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/ArticleData.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/NewsCategoryButton.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/NewsContainer.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/NewsContainerData.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/NewsItem.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/PublisherData.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/PublisherProvider.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/screen/FinanceScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/screen/NewsArticleScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/screen/NewsPublisherHomeScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/screen/NewsScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/manage/screen/ManageScreen.kt
  app/src/main/java/com/moneymate/moneymate/ui/navigation/MoneyMateNavGraph.kt
  app/src/main/java/com/moneymate/moneymate/ui/navigation/Route.kt
Labels: feat, ui

#22 [UI] 언론사 화면 로고 추가
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/PublisherData.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/component/PublisherProvider.kt
  app/src/main/java/com/moneymate/moneymate/ui/finance/screen/NewsPublisherHomeScreen.kt
  app/src/main/res/drawable/img_news_cn.png
  app/src/main/res/drawable/img_news_fnn.png
  app/src/main/res/drawable/img_news_ft.png
  app/src/main/res/drawable/img_news_hg.png
  app/src/main/res/drawable/img_news_hk.png
  app/src/main/res/drawable/img_news_mk.png
  app/src/main/res/drawable/img_news_yf.jpeg
  app/src/main/res/drawable/img_news_yn.png
Labels: ui
